name: Deploy to Azure App Service1

on:
  push:
    branches:
      - app-service-deployment

jobs:
  build-and-deploy-prod:
    runs-on: ubuntu-latest
    environment: 
      name: prodution
      url: 'githubaction-testing.azurewebsites.net'
    outputs:
      time: ${{ steps.set-time.outputs.time }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Azure App Service (Prod)
        uses: azure/webapps-deploy@v2
        with:
          app-name: githubaction-testing
          publish-profile: ${{ secrets.TEST }}
          package: .

  notification:
    runs-on: ubuntu-latest
    needs: build-and-deploy-prod
    steps:
      - name: Notify on Google Chat
        if: success()
        uses: AshwitaPal12/nodejs-app
        with:
          message: "Deployment to production environment has been done on GitHub."
          webhookUrl: '${{ secrets.APPROVAL }}'